<?php

namespace Beaver\CoreBundle;

use Beaver\CoreBundle\DependencyInjection\Compiler\WidgetPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class CoreBundle extends Bundle
{
    const BUNDLE = '@Core';

    /**
     * @param ContainerBuilder $container
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new WidgetPass());
    }

    /**
     *
     */
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
