<?php
namespace Beaver\BackendBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class ControllerBase
 * @package Beaver\BackendBundle\Controller
 */
class ControllerBase extends AbstractController
{
    /**
     * Retorna el nombre del Bundle Actual.
     * @return string
     */
    public function Bundle()
    {
        return '@BeaverBackend';
    }
    
    /**
     * Retorna el prefijo a usar en los servicios.
     * @return string
     */
    public function prefix()
    {
        return 'beaver_backend';
    }
    
    /**
     * @param string $view
     * @param array $parameters
     * @return string|Response
     */
    protected function renderView(string $view, array $parameters = array()): string
    {
        $parameters['Bundle'] = self::Bundle();
        return parent::render($view, $parameters); // TODO: Change the autogenerated stub
    }
    
    /**
     * @param string $view
     * @param array $parameters
     * @param Response|null $response
     * @return Response
     */
    public function render(string $view, array $parameters = array(), Response $response = null): Response
    {
        $parameters['Bundle']   = self::Bundle();
        $parameters['menu']     = $this->get('beaver.backend.menu')->getMenu();
        return parent::render($view, $parameters, $response);
    }
}