<?php
namespace Beaver\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class ControllerBase extends Controller
{
	/**
	 * Retorna el nombre del Bundle Actual.
	 * @return string
	 */
	/**
	 * Retorna el nombre del Bundle Actual.
	 * @return string
	 */
	protected function Bundle()
	{
		return $this->get('beaver_core.context')->getBundle();
	}
	
	/**
	 * Retorna el prefijo a usar en los servicios.
	 * @return string
	 */
	public function prefix()
	{
		$prefix = 'beaver_backend';
		if (stristr($this->get('router.request_context')->getPathInfo(), 'backend')) {
			$prefix = 'beaver_core';
		}
		
		return $prefix;
	}
	
	protected function renderView($view, array $parameters = array())
	{
		$parameters['Bundle'] = $this->Bundle();
		return parent::renderView($view, $parameters); // TODO: Change the autogenerated stub
	}
	
	protected function render($view, array $parameters = array(), Response $response = null)
	{
		if ('@BeaverBackend' === $parameters['Bundle'] = $this->Bundle()) {
			$parameters['menu'] = $this->get('beaver_backend.menu')->getMenu();
		}
		return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
	}
}