<?php
namespace Beaver\CoreBundle\Controller;

use Beaver\BackendBundle\BackendBundle;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class ControllerBase extends Controller
{
	/**
	 * Retorna el nombre del Bundle Actual.
	 * @return string
	 */
	/**
	 * Retorna el nombre del Bundle Actual.
	 * @return string
	 */
	protected function Bundle()
	{
		return $this->get('beaver.core.context')->getBundle();
	}
	
	/**
	 * Retorna el prefijo a usar en los servicios.
	 * @return string
	 */
	public function prefix()
	{
		$prefix = 'beaver_backend';
		if (stristr($this->get('router.request_context')->getPathInfo(), 'backend')) {
			$prefix = 'beaver_core';
		}
		
		return $prefix;
	}
	
	/**
	 * @param string $view
	 * @param array  $parameters
	 *
	 * @return string
	 */
	protected function renderView(string $view, array $parameters = array()): string
	{
		$parameters['Bundle'] = $this->Bundle();
		return parent::renderView($view, $parameters); // TODO: Change the autogenerated stub
	}
	
	/**
	 * @param string                                          $view
	 * @param array                                           $parameters
	 * @param Response|null                                   $response
	 *
	 * @return Response
	 */
	protected function render(string $view, array $parameters = array(), Response $response = null): Response
	{
		if (BackendBundle::BUNDLE === $parameters['Bundle'] = $this->Bundle()) {
			$parameters['menu'] = $this->get('beaver.backend.menu')->getMenu();
		}
		return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
	}
}